### ISSUE TITLE
If there are SQL failures in the scripts, dbup-cli should exit with non-zero return/exit code

### ISSUE THREAD

**Issue by spoelstraethan** [drwatson1/dbup-cli#13]
This tool is awesome and exactly what I needed to avoid duplicating the example Program.cs and app.config and csproj and sln files across multiple projects where the only difference between them is the scripts to run and the connection string (embedding SQL scripts in console program to a fixed point in time breaks my brain, I could just write a Dacpac instead of simple scripts?).

The one issue I've run into with using it in our CI pipelines is that it doesn't track and bubble up errors/exceptions to return a non-zero exit code.

Ideally it would either stop immediately with `exit 1` if it encounters an error, or perhaps more helpfully, it could try running each of the scripts it gathers from the scripts paths, and then if any fail, count how many and `exit $numberOfFailedScripts` so it becomes easy to see if you have a bad variable interpolation affecting many scripts, or an invalid query only affecting one. Adding an `on_error_action` type config option to allow users to specify `abortImmediately` or `finishFolder` or `finishAll` could provide a lot of flexibility, but potentially more complexity. 

As example of a failure that should `exit 1` to make a CI step go red, I ran a script that queries for LOGIN type users against the app database instead of `master`, this isn't valid and dbup-cli knows it, but it didn't actually fail the step in my pipeline.

```
Error Number:208,State:1,Class:16
[ERR] Upgrade failed due to an unexpected exception:
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'sys.sql_logins'.
```

**Comment by drwatson1** [comment]
I think this is a very good idea, thank you. I'll try to implement it ASAP

**Comment by drwatson1** [comment]
I tried to upgrade a database with the script

```sql
select * from NotATable
```

and got the message

```
Error Number:208,State:1,Class:16
Invalid object name 'NotATable'.
```

as expected. 

Just after executing `dbup upgrade` I tried:

```bash
> echo %errorlevel%
1
```

So the tool returned `1` instead of `0`. I used SqlExpress and ran the on Windows. It seems the `dbup` returns `1` in case of any errors. 

Can you create a simple example to help me to reproduce your problem?

**Comment by lbguilherme** [comment]
I can confirm the tool already returns `1` on failure.
