### ISSUE TITLE
PostgreSQL requires SCRAM auth / Authentication method not supported (Received: 10)

### ISSUE THREAD

**Issue by huesie** [drwatson1/dbup-cli#14]
Recent versions of postgres uses SCRAM auth (specifically SCRAM-SHA-256) and this is not currently supported in DbUp-cli.  SCRAM auth type is supported in Npgsql in v3.2.**7**+ but DbUp-cli includes Npgsql v3.2.**6** as a result of including dbup-postgresql. 
 DbUp-cli is currently broken for recent postgres 10+ that default to SCRAM/SCRAM-SHA-256 auth, giving the error message:

```Authentication method not supported (Received: 10)```

I raised [PR#602](https://github.com/DbUp/DbUp/pull/602) in dbup-postgresql and once that is merged and available in nuget then it can be upgraded in DbUp-cli.

The alternative @drwatson1 is to reference Npgsql v3.2.**7** in this project and then dbup-postgresql will then use the later version that supports SCRAM auth - any thoughts?

**Comment by drwatson1** [comment]
I see the PR is already merged, but nuget is not available yet. If this is critical for you I can build dbup-postgresql by myself an referencce it instead of nuget. After the package will be published I'll all a reference it again.

Is it appropriate for you?

**Comment by huesie** [comment]
Thanks, @drwatson1 - it is only necessary to explicitly add a reference to Npgsql v3.2.7 in DbUp-cli and this will cause dbup-postgresql to use the later version of Npgsql - that would help us massively if you would do this as an interim fix, please.

**Comment by drwatson1** [comment]
I tried to reproduce the problem but with no success. I configured a new instance of Postgres 14.1 and set it to use scram-sha-256, then run integration tests to check if the problem exists. All connections were successful.

I used this command line to run local Postgres instance (I use docker):

```bash
docker run --name pg -e POSTGRES_PASSWORD=PostgresPwd2019 -e POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256 --auth-local=scram-sha-256" -p 5432:5432 -v $PWD/pg_hba.conf:/etc/postgresql/pg_hba.conf -v $PWD/postgres.conf:/etc/postgresql/postgres.conf postgres -c config_file=/etc/postgresql/postgres.conf -c hba_file=/etc/postgresql/pg_hba.conf
```

Then I ran tests and they have passed.

```
#pg_hba.conf
local   all             all                                     scram-sha-256
# IPv4 local connections:
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             172.17.0.1/16           scram-sha-256
```

```
#postgres.conf
listen_addresses = '*'
password_encryption = scram-sha-256	# scram-sha-256 or md5
```

I'm not very good at Postgres and, possible, do something wrong.
I want to reproduce your problem to be sure, that your PR solves it, but did not succeed. For me, it seems all work fine. What do you think? 
Are you sure that the problem can be solved by updating the library version?

**Comment by huesie** [comment]
Thanks for looking at this issue @drwatson1 - I believe scram auth is now the default, so I captured the steps as I ran your test as follows with Docker Desktop ```v4.4.3``` and running under Ubuntu 20.04 under WSL2 ([with .NET 5.0 installed⇗](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-))

1. Install latest DbUp-CLI:
```
dotnet tool install --global dbup-cli
dbup --version  # shows v1.6.1 i.e. with Npgsql v3.2.6
echo $?  # yay shows 0 - thanks for fixing !
```

2. Run PostgreSQL under Docker
```
docker run --name pg -e POSTGRES_PASSWORD=PostgresPwd2019 -p 5432:5432 postgres
```

3. Run dbup ```v1.6.1``` with connection string ```Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=PostgresPwd2019``` gives me the error:
```
Authentication method not supported (Received: 10)
```

4. Download Npgsql ```v3.2.7``` and overwrite the DbUp-CLI ```Npgsql.dll``` in the installed tool folder:
(this is how we currently patch DbUp-CLI in container ... yes, it's not pretty)
```
wget --content-disposition https://www.nuget.org/api/v2/package/Npgsql/3.2.7 --directory-prefix=/tmp

unzip /tmp/npgsql.3.2.7.nupkg -d /tmp/npgsql.3.2.7

cp /tmp/npgsql.3.2.7/lib/netstandard2.0/Npgsql.dll ~/.dotnet/tools/.store/dbup-cli/1.6.1/dbup-cli/1.6.1/tools/net5.0/any/.
```

5. Re-run dbup with same connection string and it now works\
(confirms for me that just patching Npgsql.dll to v3.2.**7** is sufficient to resolve the scram auth error)


6. Uninstall DbUp-CLI as we now have a mutated installation:
```
dotnet tool uninstall --global dbup-cli
```

7. Stop postgres under docker
```
docker rm -f pg
```

**Comment by drwatson1** [comment]
I've reproduced the issue, thank you for the steps, and ready to merge your PR as a temporary solution. Great job!
