### ISSUE TITLE
dbup --version exits with (1) - i.e. a non-zero error code

### ISSUE THREAD

**Issue by huesie** [drwatson1/dbup-cli#15]
I don't think this is intended but ```dbup --version``` returns a (1) i.e. a non-zero error code and this creates issues e.g. in Dockerfile builds - is there any good reason for this and can it just return 0 exit status, please?

Here's how to reproduce this (works in bash or powershell)
```
dbup --version
echo $?
```

viz: this prints 1 in bash; and False in powershell - indicating non-zero/failure status.

**Comment by drwatson1** [comment]
You are right, this is just a bug. I'll fix it ASAP
