### ISSUE TITLE
Improved error messaging in yml parsing

### ISSUE THREAD

**Issue by Scrambles56** [drwatson1/dbup-cli#32]
So I was recently trying to setup a new Postgres project like this, and spent a bunch of time trying to solve an error I was running into. The error message I was receiving was:
```
(Line: 3, Col: 13, Idx: 66) - (Line: 3, Col: 21, Idx: 74): Exception during deserialization
```

Where I had the default `dbup init` yml config, with the one change I made being changing the provider to EXACTLY: `provider: postgres`.

I realise reading the documentation the expected value is postgresql, but it would be nice to improve the error messaging here, as I went off debugging the wrong thing (because I assumed it was a connection string problem, being the only variable thing). A simple message like "Unrecognised value for **Provider**" would be nice

**Comment by drwatson1** [comment]
Hi,

This is a good point. I'll think how to report errors more clearly.

**Comment by drwatson1** [comment]
I've made some changes and now the message is "Configuration file error: Requested value 'postgres' was not found. (Line: 3, Col: 13, Idx: 33) - (Line: 3, Col: 21, Idx: 41): Exception during deserialization". I think it can give some clue to find a problem.
