### ISSUE TITLE
Custom configuration file not always used

### ISSUE THREAD

**Issue by Huesie** [drwatson1/dbup-cli#5]
# Steps to reproduce:

## Working case
`dbup upgrade -e Default.env --ensure dbup.testdata.yml`
 ^ this works as expected - i.e. `dbup.testdata.yml` is used

## Non-working case
`dbup upgrade -e Default.env dbup.testdata.yml`
 ^ the custom config file is not used and default `dbup.yml` is erroneously used instead
 ^ note that the `--ensure` has been dropped.

## Workaround/s
- Always supply `--ensure` argument

I cloned repo and re-produced in VS2017 (.NET Core 2.1) on latest master - I will continue to try debugging and suggest a test case and fix, but am raising this possible bug so you're aware.

I'm sure original authors are much more familiar with code, so my fix may take a while, so please feel free to raise a fix if it's a confirmed bug, and I'll be happy to pull latest to test.

Thanks again for an incredibly useful addition to the dbup library - this is fantastic for pipelined database deployments - huge thanks for sharing your extensive work.

**Comment by drwatson1** [comment]
Thank you for your deep investigation :)
[This description ](https://github.com/drwatson1/dbup-cli/wiki/Command-Line-Options#upgrade) contains the explanation. The first argument for the `upgrade` command should be an optional config file name:

```bash
dbup upgrade [path-to-config/config-name.yml] [--ensure] [-e path-to-env]
```

It's amazing that my tool helps someone else but me :)

If you struck to a problem feel free to open a new issue. I'll do the best to resolve it as soon as I can.
